const publicGroupsItems = [
  {
    name: "Java Coffee Lovers",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
    category: "Cafe",
    rating: "4.7",
    visitors: "980",
    adminPic: "https://randomuser.me/api/portraits/men/1.jpg",
    adminName: "Ethan",
    currentMembers: "5",
    maxMembers: "8",
    members: [
      {
        name: "Olivia",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/women/20.jpg",
      },
      {
        name: "Noah",
        rating: "4.4",
        image: "https://randomuser.me/api/portraits/men/21.jpg",
      },
      {
        name: "Emma",
        rating: "4.3",
        image: "https://randomuser.me/api/portraits/women/22.jpg",
      },
      {
        name: "Mason",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/23.jpg",
      },
      {
        name: "Ava",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/24.jpg",
      },
    ],
  },
  {
    name: "Urban Cyclists",
    image: "https://images.unsplash.com/photo-1509395176047-4a66953fd231",
    category: "Sports",
    rating: "4.5",
    visitors: "1.3k",
    adminPic: "https://randomuser.me/api/portraits/women/2.jpg",
    adminName: "Sophia",
    currentMembers: "8",
    maxMembers: "8",
    members: [
      {
        name: "Liam",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/25.jpg",
      },
      {
        name: "Isabella",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/26.jpg",
      },
      {
        name: "James",
        rating: "4.4",
        image: "https://randomuser.me/api/portraits/men/27.jpg",
      },
      {
        name: "Mia",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/women/28.jpg",
      },
      {
        name: "Benjamin",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/29.jpg",
      },
      {
        name: "Charlotte",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/30.jpg",
      },
      {
        name: "Lucas",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/31.jpg",
      },
      {
        name: "Amelia",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/32.jpg",
      },
    ],
  },
  {
    name: "Pizza Masters",
    image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65",
    category: "Restaurant",
    rating: "4.9",
    visitors: "2.1k",
    adminPic: "https://randomuser.me/api/portraits/men/3.jpg",
    adminName: "Marco",
    currentMembers: "6",
    maxMembers: "8",
    members: [
      {
        name: "Ella",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/women/33.jpg",
      },
      {
        name: "Oliver",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/men/34.jpg",
      },
      {
        name: "Sofia",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/35.jpg",
      },
      {
        name: "Henry",
        rating: "4.4",
        image: "https://randomuser.me/api/portraits/men/36.jpg",
      },
      {
        name: "Zoe",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/women/37.jpg",
      },
      {
        name: "Jackson",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/38.jpg",
      },
    ],
  },
  {
    name: "Travel & Hike",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    category: "Travel",
    rating: "4.6",
    visitors: "850",
    adminPic: "https://randomuser.me/api/portraits/women/4.jpg",
    adminName: "Ava",
    currentMembers: "7",
    maxMembers: "8",
    members: [
      {
        name: "Ethan",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/39.jpg",
      },
      {
        name: "Madison",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/40.jpg",
      },
      {
        name: "Sebastian",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/41.jpg",
      },
      {
        name: "Chloe",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/42.jpg",
      },
      {
        name: "Daniel",
        rating: "4.4",
        image: "https://randomuser.me/api/portraits/men/43.jpg",
      },
      {
        name: "Lily",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/women/44.jpg",
      },
      {
        name: "Matthew",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/45.jpg",
      },
    ],
  },
  {
    name: "Bookworms Club",
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
    category: "Books",
    rating: "4.8",
    visitors: "1.1k",
    adminPic: "https://randomuser.me/api/portraits/men/5.jpg",
    adminName: "Liam",
    currentMembers: "7",
    maxMembers: "8",
    members: [
      {
        name: "Abigail",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/46.jpg",
      },
      {
        name: "Joseph",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/47.jpg",
      },
      {
        name: "Emily",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/women/48.jpg",
      },
      {
        name: "David",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/49.jpg",
      },
      {
        name: "Mia",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/50.jpg",
      },
      {
        name: "Andrew",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/51.jpg",
      },
      {
        name: "Charlotte",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/women/52.jpg",
      },
    ],
  },
  {
    name: "Nature Photographers",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    category: "Photography",
    rating: "4.9",
    visitors: "2.5k",
    adminPic: "https://randomuser.me/api/portraits/women/6.jpg",
    adminName: "Olivia",
    currentMembers: "8",
    maxMembers: "8",
    members: [
      {
        name: "Daniel",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/men/53.jpg",
      },
      {
        name: "Grace",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/54.jpg",
      },
      {
        name: "Joseph",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/men/55.jpg",
      },
      {
        name: "Ella",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/56.jpg",
      },
      {
        name: "David",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/57.jpg",
      },
      {
        name: "Sophia",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/women/58.jpg",
      },
      {
        name: "Matthew",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/59.jpg",
      },
      {
        name: "Madison",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/60.jpg",
      },
    ],
  },
  {
    name: "Fitness Freaks",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
    category: "Health",
    rating: "4.4",
    visitors: "740",
    adminPic: "https://randomuser.me/api/portraits/men/7.jpg",
    adminName: "Noah",
    currentMembers: "6",
    maxMembers: "8",
    members: [
      {
        name: "Lily",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/women/61.jpg",
      },
      {
        name: "James",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/62.jpg",
      },
      {
        name: "Amelia",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/63.jpg",
      },
      {
        name: "Henry",
        rating: "4.4",
        image: "https://randomuser.me/api/portraits/men/64.jpg",
      },
      {
        name: "Sofia",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/65.jpg",
      },
      {
        name: "Benjamin",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/66.jpg",
      },
    ],
  },
  {
    name: "Coding Ninjas",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    category: "Tech",
    rating: "4.9",
    visitors: "3.2k",
    adminPic: "https://randomuser.me/api/portraits/women/8.jpg",
    adminName: "Mia",
    currentMembers: "8",
    maxMembers: "8",
    members: [
      {
        name: "David",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/67.jpg",
      },
      {
        name: "Emma",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/68.jpg",
      },
      {
        name: "Michael",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/69.jpg",
      },
      {
        name: "Isabella",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/women/70.jpg",
      },
      {
        name: "Joseph",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/71.jpg",
      },
      {
        name: "Emily",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/72.jpg",
      },
      {
        name: "William",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/73.jpg",
      },
      {
        name: "Charlotte",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/74.jpg",
      },
    ],
  },
  {
    name: "Beach Volleyball",
    image: "https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf",
    category: "Sports",
    rating: "4.3",
    visitors: "620",
    adminPic: "https://randomuser.me/api/portraits/women/10.jpg",
    adminName: "Emma",
    currentMembers: "6",
    maxMembers: "8",
    members: [
      {
        name: "Lucas",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/75.jpg",
      },
      {
        name: "Ella",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/76.jpg",
      },
      {
        name: "Logan",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/77.jpg",
      },
      {
        name: "Zoe",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/78.jpg",
      },
      {
        name: "Jacob",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/men/79.jpg",
      },
      {
        name: "Mia",
        rating: "4.4",
        image: "https://randomuser.me/api/portraits/women/80.jpg",
      },
    ],
  },
  {
    name: "Art & Paint Society",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    category: "Art",
    rating: "4.8",
    visitors: "1.6k",
    adminPic: "https://randomuser.me/api/portraits/women/11.jpg",
    adminName: "Grace",
    currentMembers: "5",
    maxMembers: "8",
    members: [
      {
        name: "Michael",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/81.jpg",
      },
      {
        name: "Sophia",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/82.jpg",
      },
      {
        name: "Alexander",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/83.jpg",
      },
      {
        name: "Charlotte",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/women/84.jpg",
      },
      {
        name: "Ethan",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/men/85.jpg",
      },
    ],
  },
  {
    name: "Board Game Nights",
    image: "https://images.unsplash.com/photo-1581338834647-b0fb40704e21",
    category: "Games",
    rating: "4.7",
    visitors: "1.2k",
    adminPic: "https://randomuser.me/api/portraits/men/12.jpg",
    adminName: "Lucas",
    currentMembers: "8",
    maxMembers: "8",
    members: [
      {
        name: "Isabella",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/women/86.jpg",
      },
      {
        name: "Benjamin",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/87.jpg",
      },
      {
        name: "Amelia",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/women/88.jpg",
      },
      {
        name: "Henry",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/89.jpg",
      },
      {
        name: "Mia",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/90.jpg",
      },
      {
        name: "James",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/91.jpg",
      },
      {
        name: "Ella",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/92.jpg",
      },
      {
        name: "William",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/93.jpg",
      },
    ],
  },
  {
    name: "Street Foodies",
    image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0",
    category: "Food",
    rating: "4.5",
    visitors: "2.8k",
    adminPic: "https://randomuser.me/api/portraits/women/13.jpg",
    adminName: "Isabella",
    currentMembers: "7",
    maxMembers: "8",
    members: [
      {
        name: "Jacob",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/94.jpg",
      },
      {
        name: "Ella",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/95.jpg",
      },
      {
        name: "Ethan",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/96.jpg",
      },
      {
        name: "Grace",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/97.jpg",
      },
      {
        name: "James",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/men/98.jpg",
      },
      {
        name: "Mia",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/women/99.jpg",
      },
      {
        name: "Alexander",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/men/100.jpg",
      },
    ],
  },
  {
    name: "Pet Lovers United",
    image: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d",
    category: "Pets",
    rating: "4.9",
    visitors: "3.1k",
    adminPic: "https://randomuser.me/api/portraits/men/14.jpg",
    adminName: "Jack",
    currentMembers: "6",
    maxMembers: "8",
    members: [
      {
        name: "Charlotte",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/women/101.jpg",
      },
      {
        name: "Oliver",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/102.jpg",
      },
      {
        name: "Ella",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/women/103.jpg",
      },
      {
        name: "Henry",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/104.jpg",
      },
      {
        name: "Sophia",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/women/105.jpg",
      },
      {
        name: "James",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/106.jpg",
      },
    ],
  },
  {
    name: "Yoga Harmony",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773",
    category: "Wellness",
    rating: "4.6",
    visitors: "980",
    adminPic: "https://randomuser.me/api/portraits/women/15.jpg",
    adminName: "Ella",
    currentMembers: "5",
    maxMembers: "8",
    members: [
      {
        name: "Mason",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/107.jpg",
      },
      {
        name: "Sophia",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/women/108.jpg",
      },
      {
        name: "Jackson",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/men/109.jpg",
      },
      {
        name: "Emma",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/110.jpg",
      },
      {
        name: "Benjamin",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/111.jpg",
      },
    ],
  },
  {
    name: "Language Exchange Hub",
    image: "https://images.unsplash.com/photo-1529070538774-1843cb3265df",
    category: "Education",
    rating: "4.8",
    visitors: "1.5k",
    adminPic: "https://randomuser.me/api/portraits/men/16.jpg",
    adminName: "Oliver",
    currentMembers: "8",
    maxMembers: "8",
    members: [
      {
        name: "Mia",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/112.jpg",
      },
      {
        name: "William",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/men/113.jpg",
      },
      {
        name: "Ava",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/women/114.jpg",
      },
      {
        name: "James",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/115.jpg",
      },
      {
        name: "Isabella",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/116.jpg",
      },
      {
        name: "Liam",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/men/117.jpg",
      },
      {
        name: "Sophia",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/women/118.jpg",
      },
      {
        name: "Jacob",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/men/119.jpg",
      },
    ],
  },
  {
    name: "Mountain Bikers Crew",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd",
    category: "Sports",
    rating: "4.7",
    visitors: "1.9k",
    adminPic: "https://randomuser.me/api/portraits/women/17.jpg",
    adminName: "Zoe",
    currentMembers: "7",
    maxMembers: "8",
    members: [
      {
        name: "Ethan",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/120.jpg",
      },
      {
        name: "Madison",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/121.jpg",
      },
      {
        name: "Sebastian",
        rating: "4.8",
        image: "https://randomuser.me/api/portraits/men/122.jpg",
      },
      {
        name: "Chloe",
        rating: "4.5",
        image: "https://randomuser.me/api/portraits/women/123.jpg",
      },
      {
        name: "Daniel",
        rating: "4.9",
        image: "https://randomuser.me/api/portraits/men/124.jpg",
      },
      {
        name: "Lily",
        rating: "4.7",
        image: "https://randomuser.me/api/portraits/women/125.jpg",
      },
      {
        name: "Matthew",
        rating: "4.6",
        image: "https://randomuser.me/api/portraits/men/126.jpg",
      },
    ],
  },
];

export default publicGroupsItems;
