const publicGroupsItems = [
  {
    name: "Java Coffee Lovers",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
    category: "Cafe",
    rating: "4.7",
    visitors: "980",
    adminPic: "https://randomuser.me/api/portraits/men/1.jpg",
    adminName: "Ethan",
    currentMembers: "5",
    maxMembers: "8",
  },
  {
    name: "Urban Cyclists",
    image: "https://images.unsplash.com/photo-1509395176047-4a66953fd231",
    category: "Sports",
    rating: "4.5",
    visitors: "1.3k",
    adminPic: "https://randomuser.me/api/portraits/women/2.jpg",
    adminName: "Sophia",
    currentMembers: "8",
    maxMembers: "8",
  },
  {
    name: "Pizza Masters",
    image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65",
    category: "Restaurant",
    rating: "4.9",
    visitors: "2.1k",
    adminPic: "https://randomuser.me/api/portraits/men/3.jpg",
    adminName: "Marco",
    currentMembers: "6",
    maxMembers: "8",
  },
  {
    name: "Travel & Hike",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    category: "Travel",
    rating: "4.6",
    visitors: "850",
    adminPic: "https://randomuser.me/api/portraits/women/4.jpg",
    adminName: "Ava",
    currentMembers: "7",
    maxMembers: "8",
  },
  {
    name: "Bookworms Club",
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
    category: "Books",
    rating: "4.8",
    visitors: "1.1k",
    adminPic: "https://randomuser.me/api/portraits/men/5.jpg",
    adminName: "Liam",
    currentMembers: "7",
    maxMembers: "8",
  },
  {
    name: "Nature Photographers",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    category: "Photography",
    rating: "4.9",
    visitors: "2.5k",
    adminPic: "https://randomuser.me/api/portraits/women/6.jpg",
    adminName: "Olivia",
    currentMembers: "8",
    maxMembers: "8",
  },
  {
    name: "Fitness Freaks",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
    category: "Health",
    rating: "4.4",
    visitors: "740",
    adminPic: "https://randomuser.me/api/portraits/men/7.jpg",
    adminName: "Noah",
    currentMembers: "6",
    maxMembers: "8",
  },
  {
    name: "Coding Ninjas",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    category: "Tech",
    rating: "4.9",
    visitors: "3.2k",
    adminPic: "https://randomuser.me/api/portraits/women/8.jpg",
    adminName: "Mia",
    currentMembers: "8",
    maxMembers: "8",
  },
  {
    name: "Beach Volleyball",
    image: "https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf",
    category: "Sports",
    rating: "4.3",
    visitors: "620",
    adminPic: "https://randomuser.me/api/portraits/women/10.jpg",
    adminName: "Emma",
    currentMembers: "6",
    maxMembers: "8",
  },
  {
    name: "Art & Paint Society",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    category: "Art",
    rating: "4.8",
    visitors: "1.6k",
    adminPic: "https://randomuser.me/api/portraits/women/11.jpg",
    adminName: "Grace",
    currentMembers: "5",
    maxMembers: "8",
  },
  {
    name: "Board Game Nights",
    image: "https://images.unsplash.com/photo-1581338834647-b0fb40704e21",
    category: "Games",
    rating: "4.7",
    visitors: "1.2k",
    adminPic: "https://randomuser.me/api/portraits/men/12.jpg",
    adminName: "Lucas",
    currentMembers: "8",
    maxMembers: "8",
  },
  {
    name: "Street Foodies",
    image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0",
    category: "Food",
    rating: "4.5",
    visitors: "2.8k",
    adminPic: "https://randomuser.me/api/portraits/women/13.jpg",
    adminName: "Isabella",
    currentMembers: "7",
    maxMembers: "8",
  },
  {
    name: "Pet Lovers United",
    image: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d",
    category: "Pets",
    rating: "4.9",
    visitors: "3.1k",
    adminPic: "https://randomuser.me/api/portraits/men/14.jpg",
    adminName: "Jack",
    currentMembers: "6",
    maxMembers: "8",
  },
  {
    name: "Yoga Harmony",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773",
    category: "Wellness",
    rating: "4.6",
    visitors: "980",
    adminPic: "https://randomuser.me/api/portraits/women/15.jpg",
    adminName: "Ella",
    currentMembers: "5",
    maxMembers: "8",
  },
  {
    name: "Language Exchange Hub",
    image: "https://images.unsplash.com/photo-1529070538774-1843cb3265df",
    category: "Education",
    rating: "4.8",
    visitors: "1.5k",
    adminPic: "https://randomuser.me/api/portraits/men/16.jpg",
    adminName: "Oliver",
    currentMembers: "8",
    maxMembers: "8",
  },
  {
    name: "Mountain Bikers Crew",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd",
    category: "Sports",
    rating: "4.7",
    visitors: "1.9k",
    adminPic: "https://randomuser.me/api/portraits/women/17.jpg",
    adminName: "Zoe",
    currentMembers: "7",
    maxMembers: "8",
  },
];

export default publicGroupsItems;
